apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  namespace: test
  name: iso-cephrbd-vol1
spec:
  source:
      upload: {}
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd
